/// Flutter icons GloryIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GloryIcons
///      fonts:
///       - asset: fonts/GloryIcons.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class GloryIcons {
  GloryIcons._();

  static const _kFontFam = 'GloryIcons';
  static const String _kFontPkg = null;

  static const IconData check_circle =
      IconData(0xf058, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_empty =
      IconData(0xf10c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle =
      IconData(0xf111, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_thin =
      IconData(0xf1db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
